import { DateContextProvider } from './context/dateContext'
import './globals.css'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Pumpkin',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <DateContextProvider>
      <html lang="en">
        <body className="font-puff">{children}</body>
      </html>
    </DateContextProvider>
  )
}
