import Navbar from './components/Navbar'
import { AppContextProvider } from './context/appContext'
import './globals.css'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Pumpkin',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="font-puff">
        <AppContextProvider>
          {children}
        </AppContextProvider>
      </body>
    </html>
  )
}
